name: Build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  merge_group:
  workflow_call:
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # v6
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false
      # v4 available
      - uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3
      # v8.1.0 available
      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39
      - run: just build
      # v7
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: dist
          path: dist
          compression-level: 9
          if-no-files-found: error
